#!/bin/bash

(
version=v2.3.7
echo "Installing ETCD $version"

url="https://github.com/coreos/etcd/releases/download/$version/etcd-$version-linux-amd64.tar.gz"
echo $url
curl -L "$url" -o etcd.tgz
tar zxvf etcd.tgz
etcd_home="$PWD/etcd-$version-linux-amd64"
nohup $etcd_home/etcd &
)
